[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_BACKEND_URL = "https://sjcet-cse-feedback.onrender.com/api/v1"

# Ensure SPA routing works on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


