version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: feedback_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: student_feedback_db
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - feedback_network

  backend:
    build: ./backend
    container_name: feedback_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://admin:password@mongodb:27017/student_feedback_db?authSource=admin
      DB_NAME: student_feedback_db
      SECRET_KEY: your-super-secret-jwt-key-change-this-in-production
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      HOST: 0.0.0.0
      PORT: 8001
      LOG_LEVEL: INFO
      RATE_LIMIT_PER_MINUTE: 60
    depends_on:
      - mongodb
    networks:
      - feedback_network
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build: ./frontend
    container_name: feedback_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URL: http://localhost:8001/api
    depends_on:
      - backend
    networks:
      - feedback_network

volumes:
  mongodb_data:

networks:
  feedback_network:
    driver: bridge
